dubbo:
  application:
    name: Consumer
  registry:
    address: nacos://localhost:8848
  consumer:
    check: false
  protocol:
    name: grpc
    host: 127.0.0.1
    port: 12346

server:
  port: 9090
